language: node_js
node_js:
  - "0.8"
before_script:
  - npm install -g grunt-cli & npm install -g bower
  - gem install compass
  - bower cache clean
  - npm clear cache
  - npm install
  - bower install
script:
  - grunt
